### PR TITLE
more explanatory YAML error handling

### PR DESCRIPTION
**Pull request by CanerSezgin**
**Issue:** https://github.com/opencollective/opencollective/issues/2613

**Command:**
`curl -X POST --data-binary @.github/opencollectttp://localhost:3000/validate`

**Response:**
```
YAML file is not properly formatted:
SyntaxError: bad indentation of a mapping entry at line 65, column 5:
        labels: ['priority']
```

**TODO:** We need to change test response, could you please give me a hint how we should do that ? 
I thought we might think use if the response string contains **YAML file is not properly formatted: SyntaxError: **, it passes but need your opinion. 
Also YAML error message might be different according to error for sure. I am not specifically looking for any indentation errors. 
Such as: 

- end of the stream or a document separator is expected at line 2, column 21:
- bad indentation of a mapping entry at line 65, column 5:

### CODE REVIEW

**Comment by Betree** [comment]
> We need to change test response, could you please give me a hint how we should do that ?
I thought we might think use if the response string contains **YAML file is not properly formatted: SyntaxError: **, it passes but need your opinion.

Sounds good to me :slightly_smiling_face:

**Comment by CanerSezgin** [comment]
I have changed one of the tests from **Something went wrong.** to **YAMLException**
However, couldn't write a test for **Something went wrong.** case. What should the example scenario for this error. Any help would be perfect.

**Comment by Betree** [comment]
I'd say it's fine to not have a test for `Something went wrong`. Double-checking with @znarf

**Comment by CanerSezgin** [comment]
@Betree @znarf waiting your suggestions on this one jfyi.
I totally agree with **Betree** on _I'd say it's fine to not have a test for Something went wrong_ but on the other hand we are losing some points and codecov fails.

**Comment by Betree** [comment]
So a way to preserve the test would be to mock `yaml-js`'s `safeLoad` function to throw a random error in there. Right now we'd like to preserve the 100% test coverage so we'll go with a solution like this.

Let me know if I can further assist :slightly_smiling_face:

**Comment by Betree** [comment]
BTW @CanerSezgin would you be ok to be mentioned in our monthly contributors "Thank you" Twitter thread? If so, could you share your Twitter profile with me? Thanks!

**Comment by CanerSezgin** [comment]
@Betree Thanks in advance. Here it is.  https://twitter.com/ccanersezgin 
I'll add the test that you suggested soon. This issue's been a while, let's finish up

**Comment by CanerSezgin** [comment]
@Betree I am just unassigning me from this. Basically still we need to write a test for this case.
`return res.status(400).send('Something went wrong.')`
Unfortunately, I couldn't build a test although it seems it is not a big deal, maybe someone else can do this quickly.

**Comment by Betree** [comment]
@CanerSezgin thanks for your work on this, we'll check to add the missing test

**Review by znarf — APPROVED** [review]

**Comment by Betree** [comment]
Rebased on master & added a test for unexpected errors, coverage is back to 100%.

**Pull request merged**
